services:
  - type: web
    name: importretina
    env: static
    buildCommand: yarn && yarn build
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: true
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: X-Frame-Options
        value: sameorigin
